name: Test
on:
  push:
    branches:
      - main
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Set environment variables
        run: |
          URL=https://my-favorite-books-vite.netlify.app
          echo "PLAYWRIGHT_TEST_URL=$URL" >> $GITHUB_ENV
          echo "PLAYWRIGHT_TEST_EMAIL=${{ secrets.TEST_EMAIL }}" >> $GITHUB_ENV
          echo "PLAYWRIGHT_TEST_EMAIL=${{ secrets.TEST_PASSWORD }}" >> $GITHUB_ENV
      - name: Run tests
        run: npx playwright test